### ISSUE TITLE
Strange error with AutoSaveWorld and other..

### ISSUE THREAD

**Issue by kachekos** [MarcinWieczorek/NovaGuilds#61]
Error in console: http://pastebin.com/LXHnu7yY
And about chat. I think that plugin has conflict with ChatManager and ChatGuard. Because when i installed NG, Local  chat of ChatManager became visible for all of the players like Global..
ChatGuard doesnt stop Caps and Flood.. It doesnt send notifications to player. But if i will remove NG it will works fine :)
And about Points below players. If i  do "pointsbelowname: false" it continues to show Points below player. An if i turn off NG, it will continue to show Points under the nickname :8ball:

**Comment by MarcinWieczorek** [comment]
You still have not corrected your database config... 

The chat is being controlled by NG often making other plugins rubbish. I'm not sure how to fix that, but this is fixable only if we disable colored tags (I guess I will put this into config). 

Points below name don't dissappear because scoreboards are saved to world files. You should actually be able to disable them.

**Comment by MarcinWieczorek** [comment]
So this option can be disabled if a chat plugin is poorly written and can't utilize event priorities.
